/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jamodtester.writeCoils;

import java.awt.Color;
import javax.swing.SwingWorker;
import net.wimpi.modbus.Modbus;
import net.wimpi.modbus.ModbusCoupler;
import net.wimpi.modbus.net.ModbusTCPListener;
import net.wimpi.modbus.procimg.DigitalIn;
import net.wimpi.modbus.procimg.SimpleDigitalIn;
import net.wimpi.modbus.procimg.SimpleDigitalOut;
import net.wimpi.modbus.procimg.SimpleProcessImage;

/**
 *
 * @author Fabian
 */
public class WCSlave extends javax.swing.JFrame {
    SimpleProcessImage spi;
    ModbusTCPListener listener;
    DigitalIn coi1,coi2,coi3,coi4,coi5,coi6;
    /**
     * Creates new form RCServer
     */
    
    private class loop extends SwingWorker<Object, Object>
    {

        @Override
        protected Object doInBackground() throws Exception {
            while (true) {                
                if (ModbusCoupler.getReference().getProcessImage().getDigitalIn(0).isSet())
                    coil1.setForeground(Color.green);
                else
                    coil1.setForeground(Color.red);
                
                if (ModbusCoupler.getReference().getProcessImage().getDigitalIn(1).isSet())
                    coil2.setForeground(Color.green);
                else
                    coil2.setForeground(Color.red);
                
                if (ModbusCoupler.getReference().getProcessImage().getDigitalIn(2).isSet())
                    coil3.setForeground(Color.green);
                else
                    coil3.setForeground(Color.red);
                
                if (ModbusCoupler.getReference().getProcessImage().getDigitalIn(3).isSet())
                    coil4.setForeground(Color.green);
                else
                    coil4.setForeground(Color.red);
                
                if (ModbusCoupler.getReference().getProcessImage().getDigitalIn(4).isSet())
                    coil5.setForeground(Color.green);
                else
                    coil5.setForeground(Color.red);
                
                if (ModbusCoupler.getReference().getProcessImage().getDigitalIn(5).isSet())
                    coil6.setForeground(Color.green);
                else
                    coil6.setForeground(Color.red);
            }
        }
        
    }
    
    public WCSlave() {
        initComponents();
        
        int port = Modbus.DEFAULT_PORT;
        spi = new SimpleProcessImage();
        
        spi.addDigitalIn(new SimpleDigitalIn());
        spi.addDigitalIn(new SimpleDigitalIn());
        spi.addDigitalIn(new SimpleDigitalIn());
        spi.addDigitalIn(new SimpleDigitalIn());
        spi.addDigitalIn(new SimpleDigitalIn());
        spi.addDigitalIn(new SimpleDigitalIn());
        
        ModbusCoupler.getReference().setUnitID(Modbus.DEFAULT_UNIT_ID);
        ModbusCoupler.getReference().setMaster(false);
        ModbusCoupler.getReference().setProcessImage(spi);
        
        listener = new ModbusTCPListener(5);
        listener.setPort(port);
        listener.start();
        System.out.println("läuft");
        
        new loop().execute();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pSouth = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pMain = new javax.swing.JPanel();
        coil1 = new javax.swing.JLabel();
        coil2 = new javax.swing.JLabel();
        coil3 = new javax.swing.JLabel();
        coil4 = new javax.swing.JLabel();
        coil5 = new javax.swing.JLabel();
        coil6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pSouth.setLayout(new java.awt.CardLayout());

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pSouth.add(jButton1, "card2");

        getContentPane().add(pSouth, java.awt.BorderLayout.PAGE_END);

        pMain.setLayout(new java.awt.GridBagLayout());

        coil1.setText("Coil 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pMain.add(coil1, gridBagConstraints);

        coil2.setText("Coil 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pMain.add(coil2, gridBagConstraints);

        coil3.setText("Coil 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pMain.add(coil3, gridBagConstraints);

        coil4.setText("Coil 4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pMain.add(coil4, gridBagConstraints);

        coil5.setText("Coil 5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pMain.add(coil5, gridBagConstraints);

        coil6.setText("Coil 6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pMain.add(coil6, gridBagConstraints);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        listener.stop();
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WCSlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WCSlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WCSlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WCSlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WCSlave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coil1;
    private javax.swing.JLabel coil2;
    private javax.swing.JLabel coil3;
    private javax.swing.JLabel coil4;
    private javax.swing.JLabel coil5;
    private javax.swing.JLabel coil6;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pSouth;
    // End of variables declaration//GEN-END:variables
}
