/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jamodtester.androidSim;

import jamodtester.easyModbus.EasyModbusSlave;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.wimpi.modbus.*;


/**
 *
 * @author User
 */
public class AndroidSimSlave extends javax.swing.JFrame
{
    EasyModbusSlave slave;

  /**
   * Creates new form AndroidSimSlave
   */
    
    private class motorWorker extends SwingWorker<Object, Object>
    {
        JPanel panel;
        boolean auf;

        public motorWorker(JPanel panel, int motor) {
            this.panel = panel;
            if(motor%2 == 0) {
              this.auf = true;
            }
            else {
              this.auf = false;
            }
        }
        
        @Override
        protected Object doInBackground() throws Exception {
            panel.setBackground(Color.green);
            if(panel == pta1) {
              if(auf) {
                slave.setCoil(15, false);
              } else {
                slave.setCoil(16, false);
              }
            } else if(panel == pta2) {
              if(auf) {
                slave.setCoil(17, false);
              } else {
                slave.setCoil(18, false);
              }
            } else if(panel == pta3) {
              if(auf) {
                slave.setCoil(19, false);
              } else {
                slave.setCoil(20, false);
              }
            } else if(panel == pta4) {
              if(auf) {
                slave.setCoil(21, false);
              } else {
                slave.setCoil(22, false);
              }
            } else if(panel == pta5) {
              if(auf) {
                slave.setCoil(23, false);
              } else {
                slave.setCoil(24, false);
              }
            }
            Thread.sleep(5000);
            panel.setBackground(Color.red);
            
            if(panel == pta1) {
              if(auf) {
                slave.setCoil(16, true);
              } else {
                slave.setCoil(15, true);
              }
            } else if(panel == pta2) {
              if(auf) {
                slave.setCoil(18, true);
              } else {
                slave.setCoil(17, true);
              }
            } else if(panel == pta3) {
              if(auf) {
                slave.setCoil(20, true);
              } else {
                slave.setCoil(19, true);
              }
            } else if(panel == pta4) {
              if(auf) {
                slave.setCoil(22, true);
              } else {
                slave.setCoil(21, true);
              }
            } else if(panel == pta5) {
              if(auf) {
                slave.setCoil(24, true);
              } else {
                slave.setCoil(23, true);
              }
            }
            return 0;
        }
    }
    
    private class backgroundWorker extends SwingWorker<Object, Object>
    {

        @Override
        protected Object doInBackground() throws Exception {
            while(true)
            {
                checkMotor(0, pta1);
                checkMotor(1, ptz1);
                checkMotor(2, pta2);
                checkMotor(3, ptz2);
                checkMotor(4, pta3);
                checkMotor(5, ptz3);
                checkMotor(6, pta4);
                checkMotor(7, ptz4);
                checkMotor(8, pta5);
                checkMotor(9, ptz5);
            }
        }
        
        private void checkMotor(int motor, JPanel panel) throws Exception
        {
            if(slave.getCoil(motor))
            {
                slave.setCoil(motor, false);
                new motorWorker(panel, motor).execute();
            }
        }
    }

  public AndroidSimSlave()
  {
    initComponents();
      slave = new EasyModbusSlave(Modbus.DEFAULT_PORT, Modbus.DEFAULT_UNIT_ID, 10, 15, 0, 1);
      pta1.setBackground(Color.red);
      ptz1.setBackground(Color.red);
      pta2.setBackground(Color.red);
      ptz2.setBackground(Color.red);
      pta3.setBackground(Color.red);
      ptz3.setBackground(Color.red);
      pta4.setBackground(Color.red);
      ptz4.setBackground(Color.red);
      pta5.setBackground(Color.red);
      ptz5.setBackground(Color.red);
      slidersChanged();
      new backgroundWorker().execute();
      
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sliderMin = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sliderSec = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tbTLF = new javax.swing.JToggleButton();
        tbTSO1 = new javax.swing.JToggleButton();
        tbTSU1 = new javax.swing.JToggleButton();
        pta1 = new javax.swing.JPanel();
        ta1 = new javax.swing.JLabel();
        ptz1 = new javax.swing.JPanel();
        tz1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tbKRF = new javax.swing.JToggleButton();
        tbTSO2 = new javax.swing.JToggleButton();
        tbTSU2 = new javax.swing.JToggleButton();
        pta2 = new javax.swing.JPanel();
        ta2 = new javax.swing.JLabel();
        ptz2 = new javax.swing.JPanel();
        tz2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tbMTF = new javax.swing.JToggleButton();
        tbTSO3 = new javax.swing.JToggleButton();
        tbTSU3 = new javax.swing.JToggleButton();
        pta3 = new javax.swing.JPanel();
        ta3 = new javax.swing.JLabel();
        ptz3 = new javax.swing.JPanel();
        tz3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tbOEF = new javax.swing.JToggleButton();
        tbTSO4 = new javax.swing.JToggleButton();
        tbTSU4 = new javax.swing.JToggleButton();
        pta4 = new javax.swing.JPanel();
        ta4 = new javax.swing.JLabel();
        ptz4 = new javax.swing.JPanel();
        tz4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tbVF = new javax.swing.JToggleButton();
        tbTSO5 = new javax.swing.JToggleButton();
        tbTSU5 = new javax.swing.JToggleButton();
        pta5 = new javax.swing.JPanel();
        ta5 = new javax.swing.JLabel();
        ptz5 = new javax.swing.JPanel();
        tz5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ArduinoSimSlave");
        getContentPane().setLayout(new java.awt.BorderLayout(8, 8));

        bExit.setText("exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel3.add(bExit);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 8, 8));

        jPanel5.setLayout(new java.awt.BorderLayout(8, 0));

        jLabel1.setText("min");
        jPanel5.add(jLabel1, java.awt.BorderLayout.WEST);

        sliderMin.setMaximum(255);
        sliderMin.setValue(5);
        sliderMin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                minStateChanged(evt);
            }
        });
        jPanel5.add(sliderMin, java.awt.BorderLayout.CENTER);

        jLabel2.setText("5");
        jPanel5.add(jLabel2, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel5);

        jPanel4.setLayout(new java.awt.BorderLayout(8, 0));

        jLabel3.setText("sec");
        jPanel4.add(jLabel3, java.awt.BorderLayout.WEST);

        sliderSec.setMaximum(59);
        sliderSec.setValue(0);
        sliderSec.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderSecStateChanged(evt);
            }
        });
        jPanel4.add(sliderSec, java.awt.BorderLayout.CENTER);

        jLabel4.setText("0");
        jPanel4.add(jLabel4, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        jLabel15.setText("1");
        jPanel6.add(jLabel15);

        tbTLF.setText("TLF");
        tbTLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTLFActionPerformed(evt);
            }
        });
        jPanel6.add(tbTLF);

        tbTSO1.setText("TorSensor oben");
        tbTSO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSO1ActionPerformed(evt);
            }
        });
        jPanel6.add(tbTSO1);

        tbTSU1.setText("TorSensor unten");
        tbTSU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSU1ActionPerformed(evt);
            }
        });
        jPanel6.add(tbTSU1);

        pta1.setLayout(new java.awt.BorderLayout());

        ta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta1.setText("Tor auf");
        pta1.add(ta1, java.awt.BorderLayout.CENTER);

        jPanel6.add(pta1);

        ptz1.setLayout(new java.awt.BorderLayout());

        tz1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tz1.setText("Tor zu");
        ptz1.add(tz1, java.awt.BorderLayout.CENTER);

        jPanel6.add(ptz1);

        jPanel1.add(jPanel6);

        jLabel16.setText("2");
        jPanel7.add(jLabel16);

        tbKRF.setText("KRF");
        tbKRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKRFActionPerformed(evt);
            }
        });
        jPanel7.add(tbKRF);

        tbTSO2.setText("TorSensor oben");
        tbTSO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSO2ActionPerformed(evt);
            }
        });
        jPanel7.add(tbTSO2);

        tbTSU2.setText("TorSensor unten");
        tbTSU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSU2ActionPerformed(evt);
            }
        });
        jPanel7.add(tbTSU2);

        pta2.setLayout(new java.awt.BorderLayout());

        ta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta2.setText("Tor auf");
        pta2.add(ta2, java.awt.BorderLayout.CENTER);

        jPanel7.add(pta2);

        ptz2.setLayout(new java.awt.BorderLayout());

        tz2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tz2.setText("Tor zu");
        ptz2.add(tz2, java.awt.BorderLayout.CENTER);

        jPanel7.add(ptz2);

        jPanel1.add(jPanel7);

        jLabel17.setText("3");
        jPanel8.add(jLabel17);

        tbMTF.setText("MTF");
        tbMTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMTFActionPerformed(evt);
            }
        });
        jPanel8.add(tbMTF);

        tbTSO3.setText("TorSensor oben");
        tbTSO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSO3ActionPerformed(evt);
            }
        });
        jPanel8.add(tbTSO3);

        tbTSU3.setText("TorSensor unten");
        tbTSU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSU3ActionPerformed(evt);
            }
        });
        jPanel8.add(tbTSU3);

        pta3.setLayout(new java.awt.BorderLayout());

        ta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta3.setText("Tor auf");
        pta3.add(ta3, java.awt.BorderLayout.CENTER);

        jPanel8.add(pta3);

        ptz3.setLayout(new java.awt.BorderLayout());

        tz3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tz3.setText("Tor zu");
        ptz3.add(tz3, java.awt.BorderLayout.CENTER);

        jPanel8.add(ptz3);

        jPanel1.add(jPanel8);

        jLabel18.setText("4");
        jPanel9.add(jLabel18);

        tbOEF.setText("ÖF");
        tbOEF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbOEFActionPerformed(evt);
            }
        });
        jPanel9.add(tbOEF);

        tbTSO4.setText("TorSensor oben");
        tbTSO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSO4ActionPerformed(evt);
            }
        });
        jPanel9.add(tbTSO4);

        tbTSU4.setText("TorSensor unten");
        tbTSU4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSU4ActionPerformed(evt);
            }
        });
        jPanel9.add(tbTSU4);

        pta4.setLayout(new java.awt.BorderLayout());

        ta4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta4.setText("Tor auf");
        pta4.add(ta4, java.awt.BorderLayout.CENTER);

        jPanel9.add(pta4);

        ptz4.setLayout(new java.awt.BorderLayout());

        tz4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tz4.setText("Tor zu");
        ptz4.add(tz4, java.awt.BorderLayout.CENTER);

        jPanel9.add(ptz4);

        jPanel1.add(jPanel9);

        jLabel19.setText("5");
        jPanel10.add(jLabel19);

        tbVF.setText("VF");
        tbVF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbVFActionPerformed(evt);
            }
        });
        jPanel10.add(tbVF);

        tbTSO5.setText("TorSensor oben");
        tbTSO5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSO5ActionPerformed(evt);
            }
        });
        jPanel10.add(tbTSO5);

        tbTSU5.setText("TorSensor unten");
        tbTSU5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTSU5ActionPerformed(evt);
            }
        });
        jPanel10.add(tbTSU5);

        pta5.setLayout(new java.awt.BorderLayout());

        ta5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta5.setText("Tor auf");
        pta5.add(ta5, java.awt.BorderLayout.CENTER);

        jPanel10.add(pta5);

        ptz5.setLayout(new java.awt.BorderLayout());

        tz5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tz5.setText("Tor zu");
        ptz5.add(tz5, java.awt.BorderLayout.CENTER);

        jPanel10.add(ptz5);

        jPanel1.add(jPanel10);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slidersChanged()
    {
        slave.setRegister(0, sliderMin.getValue()*60 + sliderSec.getValue());
    }
    
  private void minStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_minStateChanged
  {//GEN-HEADEREND:event_minStateChanged
    // TODO add your handling code here:
    jLabel2.setText("" + sliderMin.getValue());
    slidersChanged();
  }//GEN-LAST:event_minStateChanged

  private void sliderSecStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_sliderSecStateChanged
  {//GEN-HEADEREND:event_sliderSecStateChanged
    // TODO add your handling code here:
    jLabel4.setText("" + sliderSec.getValue());
    slidersChanged();
  }//GEN-LAST:event_sliderSecStateChanged

  private void tbTLFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTLFActionPerformed
  {//GEN-HEADEREND:event_tbTLFActionPerformed
    try {
        slave.setCoil(10, tbTLF.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTLFActionPerformed

  private void tbTSO1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSO1ActionPerformed
  {//GEN-HEADEREND:event_tbTSO1ActionPerformed
    try {
        slave.setCoil(16, tbTSO1.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSO1ActionPerformed

  private void tbTSU1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSU1ActionPerformed
  {//GEN-HEADEREND:event_tbTSU1ActionPerformed
    try {
        slave.setCoil(15, tbTSU1.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSU1ActionPerformed

  private void tbKRFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbKRFActionPerformed
  {//GEN-HEADEREND:event_tbKRFActionPerformed
    try {
        slave.setCoil(11, tbKRF.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbKRFActionPerformed

  private void tbTSO2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSO2ActionPerformed
  {//GEN-HEADEREND:event_tbTSO2ActionPerformed
    try {
        slave.setCoil(18, tbTSO2.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSO2ActionPerformed

  private void tbTSU2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSU2ActionPerformed
  {//GEN-HEADEREND:event_tbTSU2ActionPerformed
    try {
        slave.setCoil(17, tbTSU2.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSU2ActionPerformed

  private void tbMTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbMTFActionPerformed
  {//GEN-HEADEREND:event_tbMTFActionPerformed
    try {
        slave.setCoil(12, tbMTF.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbMTFActionPerformed

  private void tbTSO3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSO3ActionPerformed
  {//GEN-HEADEREND:event_tbTSO3ActionPerformed
    try {
        slave.setCoil(20, tbTSO3.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSO3ActionPerformed

  private void tbTSU3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSU3ActionPerformed
  {//GEN-HEADEREND:event_tbTSU3ActionPerformed
    try {
        slave.setCoil(19, tbTSU3.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSU3ActionPerformed

  private void tbOEFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbOEFActionPerformed
  {//GEN-HEADEREND:event_tbOEFActionPerformed
    try {
        slave.setCoil(13, tbOEF.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbOEFActionPerformed

  private void tbTSO4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSO4ActionPerformed
  {//GEN-HEADEREND:event_tbTSO4ActionPerformed
    try {
        slave.setCoil(22, tbTSO4.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSO4ActionPerformed

  private void tbTSU4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSU4ActionPerformed
  {//GEN-HEADEREND:event_tbTSU4ActionPerformed
    try {
        slave.setCoil(21, tbTSU4.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSU4ActionPerformed

  private void tbVFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbVFActionPerformed
  {//GEN-HEADEREND:event_tbVFActionPerformed
    try {
        slave.setCoil(14, tbVF.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbVFActionPerformed

  private void tbTSO5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSO5ActionPerformed
  {//GEN-HEADEREND:event_tbTSO5ActionPerformed
    try {
        slave.setCoil(24, tbTSO5.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSO5ActionPerformed

  private void tbTSU5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbTSU5ActionPerformed
  {//GEN-HEADEREND:event_tbTSU5ActionPerformed
    try {
        slave.setCoil(23, tbTSU5.isSelected());
    } catch (Exception ex) {
        Logger.getLogger(AndroidSimSlave.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tbTSU5ActionPerformed

  private void bExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bExitActionPerformed
  {//GEN-HEADEREND:event_bExitActionPerformed
    slave.stop();
    dispose();
    System.exit(0);
  }//GEN-LAST:event_bExitActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(AndroidSimSlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(AndroidSimSlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(AndroidSimSlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(AndroidSimSlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new AndroidSimSlave().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pta1;
    private javax.swing.JPanel pta2;
    private javax.swing.JPanel pta3;
    private javax.swing.JPanel pta4;
    private javax.swing.JPanel pta5;
    private javax.swing.JPanel ptz1;
    private javax.swing.JPanel ptz2;
    private javax.swing.JPanel ptz3;
    private javax.swing.JPanel ptz4;
    private javax.swing.JPanel ptz5;
    private javax.swing.JSlider sliderMin;
    private javax.swing.JSlider sliderSec;
    private javax.swing.JLabel ta1;
    private javax.swing.JLabel ta2;
    private javax.swing.JLabel ta3;
    private javax.swing.JLabel ta4;
    private javax.swing.JLabel ta5;
    private javax.swing.JToggleButton tbKRF;
    private javax.swing.JToggleButton tbMTF;
    private javax.swing.JToggleButton tbOEF;
    private javax.swing.JToggleButton tbTLF;
    private javax.swing.JToggleButton tbTSO1;
    private javax.swing.JToggleButton tbTSO2;
    private javax.swing.JToggleButton tbTSO3;
    private javax.swing.JToggleButton tbTSO4;
    private javax.swing.JToggleButton tbTSO5;
    private javax.swing.JToggleButton tbTSU1;
    private javax.swing.JToggleButton tbTSU2;
    private javax.swing.JToggleButton tbTSU3;
    private javax.swing.JToggleButton tbTSU4;
    private javax.swing.JToggleButton tbTSU5;
    private javax.swing.JToggleButton tbVF;
    private javax.swing.JLabel tz1;
    private javax.swing.JLabel tz2;
    private javax.swing.JLabel tz3;
    private javax.swing.JLabel tz4;
    private javax.swing.JLabel tz5;
    // End of variables declaration//GEN-END:variables
}
